In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
type(list_), type(array_list)

(list, numpy.ndarray)

In [7]:
# Print data type of elements in list_
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

# Print data type of elements in array_list 
print("\nData type of elements in array_list:")
print(array_list.dtype)

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<U1


In [8]:
array_list = np.array(object=list_, dtype=int)

In [9]:
array_list

array([1, 2, 3, 4, 5])

In [10]:
array_list.dtype

dtype('int64')

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])