In [1]:
#Numpy - Array Manipulation.

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10 , (3,4))

In [4]:
arr

array([[2, 7, 6, 7],
       [9, 9, 2, 1],
       [4, 6, 2, 7]], dtype=int32)

In [5]:
arr.reshape(6,2)

array([[2, 7],
       [6, 7],
       [9, 9],
       [2, 1],
       [4, 6],
       [2, 7]], dtype=int32)

In [6]:
arr.reshape(2,6)

array([[2, 7, 6, 7, 9, 9],
       [2, 1, 4, 6, 2, 7]], dtype=int32)

In [7]:
arr.reshape(2,-242342)

array([[2, 7, 6, 7, 9, 9],
       [2, 1, 4, 6, 2, 7]], dtype=int32)

In [8]:
arr.T

array([[2, 9, 4],
       [7, 9, 6],
       [6, 2, 2],
       [7, 1, 7]], dtype=int32)

In [9]:
arr

array([[2, 7, 6, 7],
       [9, 9, 2, 1],
       [4, 6, 2, 7]], dtype=int32)

In [10]:
arr.flatten()

array([2, 7, 6, 7, 9, 9, 2, 1, 4, 6, 2, 7], dtype=int32)

In [11]:
arr1 = np.array([1,2,3,3,4])

In [12]:
arr1.ndim

1

In [13]:
np.expand_dims(arr1 ,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [14]:
np.expand_dims(arr1 ,axis=0)

array([[1, 2, 3, 3, 4]])

In [15]:
arr

array([[2, 7, 6, 7],
       [9, 9, 2, 1],
       [4, 6, 2, 7]], dtype=int32)

In [16]:
np.squeeze(arr)

array([[2, 7, 6, 7],
       [9, 9, 2, 1],
       [4, 6, 2, 7]], dtype=int32)

In [17]:
data = np.array([[1] , [2] , [3]])

In [18]:
data

array([[1],
       [2],
       [3]])

In [19]:
np.squeeze(data)

array([1, 2, 3])

In [20]:
arr1

array([1, 2, 3, 3, 4])

In [21]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [22]:
np.roll(arr1 , 3)

array([3, 3, 4, 1, 2])

In [23]:
arr1

array([1, 2, 3, 3, 4])

In [24]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [25]:
#Numpy - Binary Operators.

In [26]:
arr1 = np.random.randint(1,10 , (3,4))

In [27]:
arr2 = np.random.randint(1,10 , (3,4))

In [28]:
arr1

array([[5, 7, 6, 8],
       [8, 9, 7, 6],
       [4, 2, 9, 1]], dtype=int32)

In [29]:
arr2

array([[8, 6, 5, 8],
       [8, 8, 1, 6],
       [4, 7, 3, 8]], dtype=int32)

In [30]:
arr1+arr2

array([[13, 13, 11, 16],
       [16, 17,  8, 12],
       [ 8,  9, 12,  9]], dtype=int32)

In [31]:
arr1*arr2

array([[40, 42, 30, 64],
       [64, 72,  7, 36],
       [16, 14, 27,  8]], dtype=int32)

In [32]:
arr1/arr2

array([[0.625     , 1.16666667, 1.2       , 1.        ],
       [1.        , 1.125     , 7.        , 1.        ],
       [1.        , 0.28571429, 3.        , 0.125     ]])

In [33]:
arr1-arr2

array([[-3,  1,  1,  0],
       [ 0,  1,  6,  0],
       [ 0, -5,  6, -7]], dtype=int32)

In [34]:
arr1%arr2

array([[5, 1, 1, 0],
       [0, 1, 0, 0],
       [0, 2, 0, 1]], dtype=int32)

In [35]:
arr1 ** arr2

array([[  390625,   117649,     7776, 16777216],
       [16777216, 43046721,        7,    46656],
       [     256,      128,      729,        1]], dtype=int32)

In [36]:
arr1 & arr2

array([[0, 6, 4, 8],
       [8, 8, 1, 6],
       [4, 2, 1, 0]], dtype=int32)

In [37]:
arr1

array([[5, 7, 6, 8],
       [8, 9, 7, 6],
       [4, 2, 9, 1]], dtype=int32)

In [38]:
arr2

array([[8, 6, 5, 8],
       [8, 8, 1, 6],
       [4, 7, 3, 8]], dtype=int32)

In [39]:
~arr1

array([[ -6,  -8,  -7,  -9],
       [ -9, -10,  -8,  -7],
       [ -5,  -3, -10,  -2]], dtype=int32)

In [40]:
arr1|arr2

array([[13,  7,  7,  8],
       [ 8,  9,  7,  6],
       [ 4,  7, 11,  9]], dtype=int32)

In [41]:
arr1>arr2

array([[False,  True,  True, False],
       [False,  True,  True, False],
       [False, False,  True, False]])

In [42]:
#Numpy - String Functions.

In [43]:
arr = np.array(['sudh' , "Kumar"])

In [44]:
arr

array(['sudh', 'Kumar'], dtype='<U5')

In [45]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [46]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [47]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [48]:
#Numpy - Mathematical Functions.

In [49]:
arr1

array([[5, 7, 6, 8],
       [8, 9, 7, 6],
       [4, 2, 9, 1]], dtype=int32)

In [50]:
np.sin(arr1)

array([[-0.95892427,  0.6569866 , -0.2794155 ,  0.98935825],
       [ 0.98935825,  0.41211849,  0.6569866 , -0.2794155 ],
       [-0.7568025 ,  0.90929743,  0.41211849,  0.84147098]])

In [51]:
np.cos(arr1)

array([[ 0.28366219,  0.75390225,  0.96017029, -0.14550003],
       [-0.14550003, -0.91113026,  0.75390225,  0.96017029],
       [-0.65364362, -0.41614684, -0.91113026,  0.54030231]])

In [52]:
np.tan(arr1)

array([[-3.38051501,  0.87144798, -0.29100619, -6.79971146],
       [-6.79971146, -0.45231566,  0.87144798, -0.29100619],
       [ 1.15782128, -2.18503986, -0.45231566,  1.55740772]])

In [53]:
np.tanh(arr1)

array([[0.9999092 , 0.99999834, 0.99998771, 0.99999977],
       [0.99999977, 0.99999997, 0.99999834, 0.99998771],
       [0.9993293 , 0.96402758, 0.99999997, 0.76159416]])

In [54]:
np.log10(arr1)

array([[0.69897   , 0.84509804, 0.77815125, 0.90308999],
       [0.90308999, 0.95424251, 0.84509804, 0.77815125],
       [0.60205999, 0.30103   , 0.95424251, 0.        ]])

In [55]:
np.exp(arr1)

array([[1.48413159e+02, 1.09663316e+03, 4.03428793e+02, 2.98095799e+03],
       [2.98095799e+03, 8.10308393e+03, 1.09663316e+03, 4.03428793e+02],
       [5.45981500e+01, 7.38905610e+00, 8.10308393e+03, 2.71828183e+00]])

In [56]:
np.sqrt(arr1)

array([[2.23606798, 2.64575131, 2.44948974, 2.82842712],
       [2.82842712, 3.        , 2.64575131, 2.44948974],
       [2.        , 1.41421356, 3.        , 1.        ]])

In [57]:
np.power(arr1,2)

array([[25, 49, 36, 64],
       [64, 81, 49, 36],
       [16,  4, 81,  1]], dtype=int32)

In [58]:
np.mean(arr1)

np.float64(6.0)

In [59]:
np.median(arr1)

np.float64(6.5)

In [60]:
np.std(arr1)

np.float64(2.48327740429189)

In [61]:
np.var(arr1)

np.float64(6.166666666666667)

In [62]:
np.min(arr1
      )

np.int32(1)

In [63]:
np.max(arr1)

np.int32(9)