## Part: 01

In [1]:
import numpy as np
import pandas as pd

In [2]:
l = [1,2,3,4]

In [4]:
ar = np.array(l)

In [5]:
type(ar) #  np.narray

numpy.ndarray

In [6]:
np.array([[1,2],
          [3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [9]:
b = np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [10]:
type(b)

numpy.matrix

In [11]:
a = np.array(l)
a

array([1, 2, 3, 4])

In [12]:
c = a # value is passed by refrence(shalow copy)

In [13]:
a, c

(array([1, 2, 3, 4]), array([1, 2, 3, 4]))

In [18]:
d = np.copy(a) # array is passed by value(deep copy)

In [15]:
d

array([1, 2, 3, 4])

In [16]:
a

array([1, 2, 3, 4])

In [19]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [20]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [21]:
itreable = (i*i for i in range(5))
np.fromiter(itreable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [22]:
np.fromstring('234 345', sep=' ')

array([234., 345.])

In [23]:
np.fromstring('4,5', sep=',')

array([4., 5.])

In [24]:
# Numpy: DataTypes

In [25]:
l = [2,3,4,5,6]
ar = np.array(l)
ar

array([2, 3, 4, 5, 6])

In [26]:
ar.ndim

1

In [27]:
ar2 = np.array([[1,2,3,4],
                [2,3,4,5]])
ar2.ndim

2

In [28]:
ar.size, ar2.size

(5, 8)

In [29]:
ar.shape, ar2.shape

((5,), (2, 4))

In [31]:
ar.dtype, ar2.dtype

(dtype('int64'), dtype('int64'))

In [33]:
ar22 = np.array([(1.4, 45, 45),
                 (23,45,66)])
ar22.dtype

dtype('float64')

In [34]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [37]:
list(range(5)) # range always takes interger never float

[0, 1, 2, 3, 4]

In [39]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [41]:
np.linspace(1,5,10) # creates 10 space value is in between (1,5)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [43]:
np.zeros(5) # 1d array with 5 spaces

array([0., 0., 0., 0., 0.])

In [44]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
ones = np.ones((2,3,2))

In [46]:
ones

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [47]:
ones+1

array([[[2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.]]])

In [48]:
ones*2

array([[[2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.]]])

In [50]:
np.empty((3,5))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 2.17965616e-306]])

In [51]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
np.logspace(2,3, 4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [56]:
arr = np.random.randn(3,4) # mean=0, std=1

In [97]:
np.random.rand(3,4) # random value

array([[0.11894769, 0.23629223, 0.47121842, 0.78719702],
       [0.44342699, 0.79281586, 0.8641185 , 0.85455659],
       [0.70117954, 0.51607482, 0.58325644, 0.30794061]])

In [59]:
np.random.randint(1,200, (3,4)) # range: 1,200 shape: (3,4) only generates integer value

array([[ 94,  89,  71, 108],
       [ 38, 134,  82, 106],
       [128,  23, 183, 143]], dtype=int32)

In [61]:
arr = np.random.rand(3,4)

In [62]:
arr

array([[0.47139886, 0.43567172, 0.14649336, 0.72589829],
       [0.96552687, 0.60453778, 0.80590908, 0.92052262],
       [0.19114849, 0.82945644, 0.61252277, 0.05355323]])

In [64]:
arr.reshape(4,3) # r*c == r'*c'

array([[0.47139886, 0.43567172, 0.14649336],
       [0.72589829, 0.96552687, 0.60453778],
       [0.80590908, 0.92052262, 0.19114849],
       [0.82945644, 0.61252277, 0.05355323]])

In [65]:
arr.reshape(6,2)

array([[0.47139886, 0.43567172],
       [0.14649336, 0.72589829],
       [0.96552687, 0.60453778],
       [0.80590908, 0.92052262],
       [0.19114849, 0.82945644],
       [0.61252277, 0.05355323]])

In [66]:
arr.reshape(12,1)

array([[0.47139886],
       [0.43567172],
       [0.14649336],
       [0.72589829],
       [0.96552687],
       [0.60453778],
       [0.80590908],
       [0.92052262],
       [0.19114849],
       [0.82945644],
       [0.61252277],
       [0.05355323]])

In [67]:
arr1 = arr.reshape(6,2)

In [68]:
arr1

array([[0.47139886, 0.43567172],
       [0.14649336, 0.72589829],
       [0.96552687, 0.60453778],
       [0.80590908, 0.92052262],
       [0.19114849, 0.82945644],
       [0.61252277, 0.05355323]])

In [71]:
arr1[1:4, 1]

array([0.72589829, 0.60453778, 0.92052262])

In [72]:
arr = np.random.randint(1,100, (5,5))
arr

array([[29, 21, 91,  6, 28],
       [47, 67,  1, 67, 11],
       [78, 82, 55,  1, 41],
       [27, 10, 73, 75, 73],
       [ 2, 47, 75, 69, 49]], dtype=int32)

In [73]:
# find all the value greater than 50
arr>50

array([[False, False,  True, False, False],
       [False,  True, False,  True, False],
       [ True,  True,  True, False, False],
       [False, False,  True,  True,  True],
       [False, False,  True,  True, False]])

In [74]:
arr[arr>50]

array([91, 67, 67, 78, 82, 55, 73, 75, 73, 75, 69], dtype=int32)

In [75]:
arr

array([[29, 21, 91,  6, 28],
       [47, 67,  1, 67, 11],
       [78, 82, 55,  1, 41],
       [27, 10, 73, 75, 73],
       [ 2, 47, 75, 69, 49]], dtype=int32)

In [76]:
arr[2:4, 1:3]

array([[82, 55],
       [10, 73]], dtype=int32)

In [77]:
# Inbuild methods

In [78]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [79]:
arr1+arr2

array([[3, 3, 3],
       [3, 3, 2],
       [2, 3, 2]], dtype=int32)

In [80]:
arr1

array([[2, 1, 1],
       [1, 1, 1],
       [1, 2, 1]], dtype=int32)

In [81]:
arr2

array([[1, 2, 2],
       [2, 2, 1],
       [1, 1, 1]], dtype=int32)

In [82]:
arr1*arr2 #normal multiplication    

array([[2, 2, 2],
       [2, 2, 1],
       [1, 2, 1]], dtype=int32)

In [83]:
# broad casting

In [86]:
arr = np.zeros((4,4))

In [87]:
row = np.array([1,2,3,4])

In [89]:
arr + row #row array is broadcasting on arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [101]:
arr = arr + 10

In [103]:
arr

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [105]:
np.exp(arr)

array([[22026.46579481, 22026.46579481, 22026.46579481, 22026.46579481],
       [22026.46579481, 22026.46579481, 22026.46579481, 22026.46579481],
       [22026.46579481, 22026.46579481, 22026.46579481, 22026.46579481],
       [22026.46579481, 22026.46579481, 22026.46579481, 22026.46579481]])

In [106]:
np.log10(arr)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [104]:
np.sqrt(arr)

array([[3.16227766, 3.16227766, 3.16227766, 3.16227766],
       [3.16227766, 3.16227766, 3.16227766, 3.16227766],
       [3.16227766, 3.16227766, 3.16227766, 3.16227766],
       [3.16227766, 3.16227766, 3.16227766, 3.16227766]])

## Part: 02

In [107]:
arr = np.random.randint(1,10, (3,4))
arr

array([[7, 9, 6, 2],
       [1, 3, 3, 3],
       [9, 4, 2, 1]], dtype=int32)

In [108]:
arr.reshape(6,2)

array([[7, 9],
       [6, 2],
       [1, 3],
       [3, 3],
       [9, 4],
       [2, 1]], dtype=int32)

In [109]:
arr.T

array([[7, 1, 9],
       [9, 3, 4],
       [6, 3, 2],
       [2, 3, 1]], dtype=int32)

In [110]:
arr.flatten()

array([7, 9, 6, 2, 1, 3, 3, 3, 9, 4, 2, 1], dtype=int32)

In [111]:
arr1 = np.array([1,2,3,3,4])

In [112]:
arr1

array([1, 2, 3, 3, 4])

In [113]:
arr1.ndim

1

In [119]:
np.expand_dims(arr1, axis=1).shape

(5, 1)

In [118]:
np.expand_dims(arr1, axis=0).shape

(1, 5)

In [120]:
data = np.array([[1], [2], [3]])

In [121]:
data.shape

(3, 1)

In [122]:
np.squeeze(data).shape

(3,)